# Generated by Django 2.0.3 on 2018-04-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationInfo_Course', models.CharField(max_length=100)),
                ('EducationInfo_Course_Duration', models.CharField(max_length=100)),
                ('EducationInfo_Course_Detail', models.CharField(max_length=100)),
                ('EducationInfo_Institute', models.CharField(max_length=100)),
                ('EducationInfo_Passing_Year', models.CharField(max_length=100)),
                ('EducationInfo_Modified_Date', models.DateField(auto_now_add=True)),
                ('EducationInfo_Created_Time', models.DateField(auto_now_add=True)),
                ('EducationInfo_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationInfos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
