# Generated by Django 2.0.3 on 2018-04-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileProject_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('ProfileProject_Updated_Date', models.DateTimeField(auto_now=True)),
                ('ProfileProject_Image', models.ImageField(upload_to='')),
                ('Profile_Project_Video', models.FileField(upload_to='')),
                ('ProfileProject_Category', models.CharField(max_length=200)),
                ('ProfileProject_Director', models.CharField(max_length=200)),
                ('ProfileProject_Production_House', models.CharField(max_length=200)),
                ('ProfileProject_Title', models.CharField(max_length=200)),
                ('ProfileProject_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileProjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
