# Generated by Django 2.0.3 on 2018-04-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating_Create_Date', models.DateTimeField(auto_now_add=True)),
                ('Rating_Modified_Date', models.DateTimeField(auto_now=True)),
                ('Rating', models.IntegerField()),
                ('Rating_User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
