# Generated by Django 2.0.3 on 2018-04-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PortfolioElement_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('PortfolioElement_Updated_Date', models.DateTimeField(auto_now=True)),
                ('PortfolioElement_VideoAudio', models.FileField(upload_to='')),
                ('PortfolioElement_Image', models.ImageField(max_length=200, upload_to='')),
                ('PortfolioElement_Title', models.CharField(max_length=200)),
                ('PortfolioElement_Category', models.CharField(max_length=200)),
                ('PortfolioElement_Director', models.CharField(max_length=200)),
                ('PortfolioElement_Production_House', models.CharField(max_length=200)),
                ('portfolioElement_Message', models.CharField(max_length=200)),
                ('PortfolioElement_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_element', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
