# Generated by Django 2.0.3 on 2018-04-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserDetail_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('UserDetail_First_Name', models.CharField(max_length=200)),
                ('UserDetail_Last_Name', models.CharField(max_length=200)),
                ('UserDetails_Phone', models.IntegerField()),
                ('UserDetail_Date_Of_Birth', models.DateField()),
                ('UserDetail_Gender', models.CharField(max_length=200)),
                ('UserDetail_Street_Address', models.CharField(max_length=200)),
                ('UserDetail_City', models.CharField(max_length=200)),
                ('UserDetail_State', models.CharField(max_length=200)),
                ('UserDetail_Country', models.CharField(max_length=200)),
                ('UserDetail_Pin_Code', models.IntegerField()),
                ('UserDetail_Profile_Picture', models.ImageField(upload_to='')),
                ('UserDetail_User_Description', models.CharField(max_length=200)),
                ('UserDetail_Completed', models.BooleanField(default=True)),
                ('UserDetail_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
