# Generated by Django 2.0.3 on 2018-04-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Financial_Available', models.BooleanField(default=False)),
                ('Financial_Crew_Size_Negotiablity', models.BooleanField(default=False)),
                ('Financial_Duration_Negotiablity', models.BooleanField(default=False)),
                ('Financial_Crew_Size_Negotiablity_student', models.IntegerField()),
                ('Financial_Crew_Size_Negotiablity_TV', models.IntegerField()),
                ('Financial_Crew_Size_Negotiablity_Film', models.IntegerField()),
                ('Financial_Daily_Charges', models.IntegerField()),
                ('Financial_Weekly_Charges', models.IntegerField()),
                ('Financial_Montly_Charges', models.IntegerField()),
                ('Financial_Negotiated_Charges', models.IntegerField()),
            ],
        ),
    ]
