# Generated by Django 2.0.3 on 2018-04-06 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor_Modified_Date', models.DateTimeField(auto_now=True)),
                ('Actor_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Actor_Body_Type', models.CharField(choices=[('THIN', 'Thin'), ('SLIM', 'Slim'), ('ATHLETIC', 'Athletic'), ('HEALTHY', 'Healthy'), ('HEAVY', 'Heavy'), ('BULKY', 'Bulky')], max_length=100)),
                ('Actor_Ethnicity', models.CharField(choices=[('Indian', 'Indian'), ('Dravidian', 'Dravidian'), ('Tamils', 'Tamils'), ('Malayali', 'Malayali'), ('Kannada', 'Kannada'), ('Naga', 'Naga'), ('Bengalis', 'Bengalis'), ('Munda', 'Munda'), ('Arabs', 'Arabs'), ('parsi', 'parsi'), ('Dogra', 'Dogra'), ('Kashmiris', 'Kashmiris'), ('Non-resident Indian and Person of Indian Origin', 'Non-resident Indian and Person of Indian Origin'), ('Mizo', 'Mizo'), ('Tais', 'Tais'), ('Sindhis', 'Sindhis'), ('Romani', 'Romani'), ('Telugu', 'Telugu'), ('East Indians', 'East Indians'), ('Sikkimese', 'Sikkimese'), ('odia', 'odia'), ('khasi', 'khasi'), ('Chakma', 'Chakma'), ('Meitei', 'Meitei'), ('Marwari', 'Marwari'), ('Irula', 'Irula'), ('White', 'White'), ('Dardic', 'Dardic'), ('Khonds', 'Khonds'), ('Luso-Indian', 'Luso-Indian'), ('Tibetan', 'Tibetan'), ('Tharu', 'Tharu'), ('Anglo-Indian', 'Anglo-Indian'), ('Garhwali', 'Garhwali'), ('Arab', 'Arab'), ('Black', 'Black'), ('Afro American', 'Afro American'), ('Russian', 'Russian'), ('European', 'European'), ('American', 'American'), ('Australian', 'Australian'), ('Others', 'Others')], max_length=100)),
                ('Actor_Eye_Color', models.CharField(choices=[('AMBER', 'Amber'), ('BLUE', 'Blue'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('GREEN', 'Green'), ('HAZEL', 'Hazel'), ('RED AND VIOLET', 'Red And Violet')], max_length=100)),
                ('Actor_Favorite_Acting_Styles', models.CharField(choices=[('Uta Hagen', 'Uta Hagen'), ('Herbert Berghof', 'Herbert Berghof'), ('Leestrasberg', 'Leestrasberg'), ('Sandy Meisner', 'Sandy Meisner'), ('Stella Adler', 'Stella Adler'), ('Alexander Technique', 'Alexander Technique'), ('Method Acting', 'Method Acting'), ('Stanislavsky', 'Stanislavsky'), ('Michael Chekhov', 'Michael Chekhov'), ('other', 'other ')], max_length=100)),
                ('Actor_Height', models.CharField(max_length=100)),
                ('Actor_Language', models.CharField(max_length=100)),
                ('Actor_SceneComfort', models.CharField(choices=[('COVERED', 'Covered'), ('SEMI NUDE', 'Semi Nude'), ('UNDER GARMENTS/BIKINE', 'Under Garments/Bikini'), ('FRONTAL NUDE', 'Frontal Nude'), ('NUDE', 'Nude')], max_length=100)),
                ('Actor_Skin_Color', models.CharField(choices=[('WHITE,FAIR', 'White,Fair'), ('MEDIUM,WHITE TO LIGHT BROWN', 'Medium,White To Light Brown'), ('OLIVE,MODERATE BROWN', 'Olive,Moderate Brown'), ('BROWN,DARK BROWN', 'Brown,Dark Brown'), ('BLACK,DARK', 'Black,Dark')], max_length=100)),
                ('Actor_Smoker', models.BooleanField(default=False)),
                ('Actor_Special_skill', models.TextField(max_length=500)),
                ('Actor_Weight', models.CharField(max_length=100)),
                ('Actor_Description', models.TextField(max_length=100)),
                ('Actor_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors_Creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
